<ul id="bootstrap" class="list-icon localsearch"  data-font="Glyphicons Halflings">
    <li class="search-show"><i class="glyphicon glyphicon-asterisk " data-hex="&quot;\2a&quot;"></i>glyphicon glyphicon-asterisk </li>
    <li class="search-show"><i class="glyphicon glyphicon-plus " data-hex="&quot;\2b&quot;"></i>glyphicon glyphicon-plus </li>
    <li class="search-show"><i class="glyphicon glyphicon-euro" data-hex="&quot;\20ac&quot;"></i>glyphicon glyphicon-euro<br><small title="
glyphicon-euro | 
glyphicon-eur  " class="help">2 alias</small> </li>
    <li class="search-show"><i class="glyphicon glyphicon-eur " data-hex="&quot;\20ac&quot;"></i>glyphicon glyphicon-eur <br><small title="
glyphicon-euro | 
glyphicon-eur  " class="help">2 alias</small> </li>
    <li class="search-show"><i class="glyphicon glyphicon-minus " data-hex="&quot;\2212&quot;"></i>glyphicon glyphicon-minus </li>
    <li class="search-show"><i class="glyphicon glyphicon-cloud " data-hex="&quot;\2601&quot;"></i>glyphicon glyphicon-cloud </li>
    <li class="search-show"><i class="glyphicon glyphicon-envelope " data-hex="&quot;\2709&quot;"></i>glyphicon glyphicon-envelope </li>
    <li class="search-show"><i class="glyphicon glyphicon-pencil " data-hex="&quot;\270f&quot;"></i>glyphicon glyphicon-pencil </li>
    <li class="search-show"><i class="glyphicon glyphicon-glass " data-hex="&quot;\e001&quot;"></i>glyphicon glyphicon-glass </li>
    <li class="search-show"><i class="glyphicon glyphicon-music " data-hex="&quot;\e002&quot;"></i>glyphicon glyphicon-music </li>
    <li class="search-show"><i class="glyphicon glyphicon-search " data-hex="&quot;\e003&quot;"></i>glyphicon glyphicon-search </li>
    <li class="search-show"><i class="glyphicon glyphicon-heart " data-hex="&quot;\e005&quot;"></i>glyphicon glyphicon-heart </li>
    <li class="search-show"><i class="glyphicon glyphicon-star " data-hex="&quot;\e006&quot;"></i>glyphicon glyphicon-star </li>
    <li class="search-show"><i class="glyphicon glyphicon-star-empty " data-hex="&quot;\e007&quot;"></i>glyphicon glyphicon-star-empty </li>
    <li class="search-show"><i class="glyphicon glyphicon-user " data-hex="&quot;\e008&quot;"></i>glyphicon glyphicon-user </li>
    <li class="search-show"><i class="glyphicon glyphicon-film " data-hex="&quot;\e009&quot;"></i>glyphicon glyphicon-film </li>
    <li class="search-show"><i class="glyphicon glyphicon-th-large " data-hex="&quot;\e010&quot;"></i>glyphicon glyphicon-th-large </li>
    <li class="search-show"><i class="glyphicon glyphicon-th " data-hex="&quot;\e011&quot;"></i>glyphicon glyphicon-th </li>
    <li class="search-show"><i class="glyphicon glyphicon-th-list " data-hex="&quot;\e012&quot;"></i>glyphicon glyphicon-th-list </li>
    <li class="search-show"><i class="glyphicon glyphicon-ok " data-hex="&quot;\e013&quot;"></i>glyphicon glyphicon-ok </li>
    <li class="search-show"><i class="glyphicon glyphicon-remove " data-hex="&quot;\e014&quot;"></i>glyphicon glyphicon-remove </li>
    <li class="search-show"><i class="glyphicon glyphicon-zoom-in " data-hex="&quot;\e015&quot;"></i>glyphicon glyphicon-zoom-in </li>
    <li class="search-show"><i class="glyphicon glyphicon-zoom-out " data-hex="&quot;\e016&quot;"></i>glyphicon glyphicon-zoom-out </li>
    <li class="search-show"><i class="glyphicon glyphicon-off " data-hex="&quot;\e017&quot;"></i>glyphicon glyphicon-off </li>
    <li class="search-show"><i class="glyphicon glyphicon-signal " data-hex="&quot;\e018&quot;"></i>glyphicon glyphicon-signal </li>
    <li class="search-show"><i class="glyphicon glyphicon-cog " data-hex="&quot;\e019&quot;"></i>glyphicon glyphicon-cog </li>
    <li class="search-show"><i class="glyphicon glyphicon-trash " data-hex="&quot;\e020&quot;"></i>glyphicon glyphicon-trash </li>
    <li class="search-show"><i class="glyphicon glyphicon-home " data-hex="&quot;\e021&quot;"></i>glyphicon glyphicon-home </li>
    <li class="search-show"><i class="glyphicon glyphicon-file " data-hex="&quot;\e022&quot;"></i>glyphicon glyphicon-file </li>
    <li class="search-show"><i class="glyphicon glyphicon-time " data-hex="&quot;\e023&quot;"></i>glyphicon glyphicon-time </li>
    <li class="search-show"><i class="glyphicon glyphicon-road " data-hex="&quot;\e024&quot;"></i>glyphicon glyphicon-road </li>
    <li class="search-show"><i class="glyphicon glyphicon-download-alt " data-hex="&quot;\e025&quot;"></i>glyphicon glyphicon-download-alt </li>
    <li class="search-show"><i class="glyphicon glyphicon-download " data-hex="&quot;\e026&quot;"></i>glyphicon glyphicon-download </li>
    <li class="search-show"><i class="glyphicon glyphicon-upload " data-hex="&quot;\e027&quot;"></i>glyphicon glyphicon-upload </li>
    <li class="search-show"><i class="glyphicon glyphicon-inbox " data-hex="&quot;\e028&quot;"></i>glyphicon glyphicon-inbox </li>
    <li class="search-show"><i class="glyphicon glyphicon-play-circle " data-hex="&quot;\e029&quot;"></i>glyphicon glyphicon-play-circle </li>
    <li class="search-show"><i class="glyphicon glyphicon-repeat " data-hex="&quot;\e030&quot;"></i>glyphicon glyphicon-repeat </li>
    <li class="search-show"><i class="glyphicon glyphicon-refresh " data-hex="&quot;\e031&quot;"></i>glyphicon glyphicon-refresh </li>
    <li class="search-show"><i class="glyphicon glyphicon-list-alt " data-hex="&quot;\e032&quot;"></i>glyphicon glyphicon-list-alt </li>
    <li class="search-show"><i class="glyphicon glyphicon-lock " data-hex="&quot;\e033&quot;"></i>glyphicon glyphicon-lock </li>
    <li class="search-show"><i class="glyphicon glyphicon-flag " data-hex="&quot;\e034&quot;"></i>glyphicon glyphicon-flag </li>
    <li class="search-show"><i class="glyphicon glyphicon-headphones " data-hex="&quot;\e035&quot;"></i>glyphicon glyphicon-headphones </li>
    <li class="search-show"><i class="glyphicon glyphicon-volume-off " data-hex="&quot;\e036&quot;"></i>glyphicon glyphicon-volume-off </li>
    <li class="search-show"><i class="glyphicon glyphicon-volume-down " data-hex="&quot;\e037&quot;"></i>glyphicon glyphicon-volume-down </li>
    <li class="search-show"><i class="glyphicon glyphicon-volume-up " data-hex="&quot;\e038&quot;"></i>glyphicon glyphicon-volume-up </li>
    <li class="search-show"><i class="glyphicon glyphicon-qrcode " data-hex="&quot;\e039&quot;"></i>glyphicon glyphicon-qrcode </li>
    <li class="search-show"><i class="glyphicon glyphicon-barcode " data-hex="&quot;\e040&quot;"></i>glyphicon glyphicon-barcode </li>
    <li class="search-show"><i class="glyphicon glyphicon-tag " data-hex="&quot;\e041&quot;"></i>glyphicon glyphicon-tag </li>
    <li class="search-show"><i class="glyphicon glyphicon-tags " data-hex="&quot;\e042&quot;"></i>glyphicon glyphicon-tags </li>
    <li class="search-show"><i class="glyphicon glyphicon-book " data-hex="&quot;\e043&quot;"></i>glyphicon glyphicon-book </li>
    <li class="search-show"><i class="glyphicon glyphicon-bookmark " data-hex="&quot;\e044&quot;"></i>glyphicon glyphicon-bookmark </li>
    <li class="search-show"><i class="glyphicon glyphicon-print " data-hex="&quot;\e045&quot;"></i>glyphicon glyphicon-print </li>
    <li class="search-show"><i class="glyphicon glyphicon-camera " data-hex="&quot;\e046&quot;"></i>glyphicon glyphicon-camera </li>
    <li class="search-show"><i class="glyphicon glyphicon-font " data-hex="&quot;\e047&quot;"></i>glyphicon glyphicon-font </li>
    <li class="search-show"><i class="glyphicon glyphicon-bold " data-hex="&quot;\e048&quot;"></i>glyphicon glyphicon-bold </li>
    <li class="search-show"><i class="glyphicon glyphicon-italic " data-hex="&quot;\e049&quot;"></i>glyphicon glyphicon-italic </li>
    <li class="search-show"><i class="glyphicon glyphicon-text-height " data-hex="&quot;\e050&quot;"></i>glyphicon glyphicon-text-height </li>
    <li class="search-show"><i class="glyphicon glyphicon-text-width " data-hex="&quot;\e051&quot;"></i>glyphicon glyphicon-text-width </li>
    <li class="search-show"><i class="glyphicon glyphicon-align-left " data-hex="&quot;\e052&quot;"></i>glyphicon glyphicon-align-left </li>
    <li class="search-show"><i class="glyphicon glyphicon-align-center " data-hex="&quot;\e053&quot;"></i>glyphicon glyphicon-align-center </li>
    <li class="search-show"><i class="glyphicon glyphicon-align-right " data-hex="&quot;\e054&quot;"></i>glyphicon glyphicon-align-right </li>
    <li class="search-show"><i class="glyphicon glyphicon-align-justify " data-hex="&quot;\e055&quot;"></i>glyphicon glyphicon-align-justify </li>
    <li class="search-show"><i class="glyphicon glyphicon-list " data-hex="&quot;\e056&quot;"></i>glyphicon glyphicon-list </li>
    <li class="search-show"><i class="glyphicon glyphicon-indent-left " data-hex="&quot;\e057&quot;"></i>glyphicon glyphicon-indent-left </li>
    <li class="search-show"><i class="glyphicon glyphicon-indent-right " data-hex="&quot;\e058&quot;"></i>glyphicon glyphicon-indent-right </li>
    <li class="search-show"><i class="glyphicon glyphicon-facetime-video " data-hex="&quot;\e059&quot;"></i>glyphicon glyphicon-facetime-video </li>
    <li class="search-show"><i class="glyphicon glyphicon-picture " data-hex="&quot;\e060&quot;"></i>glyphicon glyphicon-picture </li>
    <li class="search-show"><i class="glyphicon glyphicon-map-marker " data-hex="&quot;\e062&quot;"></i>glyphicon glyphicon-map-marker </li>
    <li class="search-show"><i class="glyphicon glyphicon-adjust " data-hex="&quot;\e063&quot;"></i>glyphicon glyphicon-adjust </li>
    <li class="search-show"><i class="glyphicon glyphicon-tint " data-hex="&quot;\e064&quot;"></i>glyphicon glyphicon-tint </li>
    <li class="search-show"><i class="glyphicon glyphicon-edit " data-hex="&quot;\e065&quot;"></i>glyphicon glyphicon-edit </li>
    <li class="search-show"><i class="glyphicon glyphicon-share " data-hex="&quot;\e066&quot;"></i>glyphicon glyphicon-share </li>
    <li class="search-show"><i class="glyphicon glyphicon-check " data-hex="&quot;\e067&quot;"></i>glyphicon glyphicon-check </li>
    <li class="search-show"><i class="glyphicon glyphicon-move " data-hex="&quot;\e068&quot;"></i>glyphicon glyphicon-move </li>
    <li class="search-show"><i class="glyphicon glyphicon-step-backward " data-hex="&quot;\e069&quot;"></i>glyphicon glyphicon-step-backward </li>
    <li class="search-show"><i class="glyphicon glyphicon-fast-backward " data-hex="&quot;\e070&quot;"></i>glyphicon glyphicon-fast-backward </li>
    <li class="search-show"><i class="glyphicon glyphicon-backward " data-hex="&quot;\e071&quot;"></i>glyphicon glyphicon-backward </li>
    <li class="search-show"><i class="glyphicon glyphicon-play " data-hex="&quot;\e072&quot;"></i>glyphicon glyphicon-play </li>
    <li class="search-show"><i class="glyphicon glyphicon-pause " data-hex="&quot;\e073&quot;"></i>glyphicon glyphicon-pause </li>
    <li class="search-show"><i class="glyphicon glyphicon-stop " data-hex="&quot;\e074&quot;"></i>glyphicon glyphicon-stop </li>
    <li class="search-show"><i class="glyphicon glyphicon-forward " data-hex="&quot;\e075&quot;"></i>glyphicon glyphicon-forward </li>
    <li class="search-show"><i class="glyphicon glyphicon-fast-forward " data-hex="&quot;\e076&quot;"></i>glyphicon glyphicon-fast-forward </li>
    <li class="search-show"><i class="glyphicon glyphicon-step-forward " data-hex="&quot;\e077&quot;"></i>glyphicon glyphicon-step-forward </li>
    <li class="search-show"><i class="glyphicon glyphicon-eject " data-hex="&quot;\e078&quot;"></i>glyphicon glyphicon-eject </li>
    <li class="search-show"><i class="glyphicon glyphicon-chevron-left " data-hex="&quot;\e079&quot;"></i>glyphicon glyphicon-chevron-left </li>
    <li class="search-show"><i class="glyphicon glyphicon-chevron-right " data-hex="&quot;\e080&quot;"></i>glyphicon glyphicon-chevron-right </li>
    <li class="search-show"><i class="glyphicon glyphicon-plus-sign " data-hex="&quot;\e081&quot;"></i>glyphicon glyphicon-plus-sign </li>
    <li class="search-show"><i class="glyphicon glyphicon-minus-sign " data-hex="&quot;\e082&quot;"></i>glyphicon glyphicon-minus-sign </li>
    <li class="search-show"><i class="glyphicon glyphicon-remove-sign " data-hex="&quot;\e083&quot;"></i>glyphicon glyphicon-remove-sign </li>
    <li class="search-show"><i class="glyphicon glyphicon-ok-sign " data-hex="&quot;\e084&quot;"></i>glyphicon glyphicon-ok-sign </li>
    <li class="search-show"><i class="glyphicon glyphicon-question-sign " data-hex="&quot;\e085&quot;"></i>glyphicon glyphicon-question-sign </li>
    <li class="search-show"><i class="glyphicon glyphicon-info-sign " data-hex="&quot;\e086&quot;"></i>glyphicon glyphicon-info-sign </li>
    <li class="search-show"><i class="glyphicon glyphicon-screenshot " data-hex="&quot;\e087&quot;"></i>glyphicon glyphicon-screenshot </li>
    <li class="search-show"><i class="glyphicon glyphicon-remove-circle " data-hex="&quot;\e088&quot;"></i>glyphicon glyphicon-remove-circle </li>
    <li class="search-show"><i class="glyphicon glyphicon-ok-circle " data-hex="&quot;\e089&quot;"></i>glyphicon glyphicon-ok-circle </li>
    <li class="search-show"><i class="glyphicon glyphicon-ban-circle " data-hex="&quot;\e090&quot;"></i>glyphicon glyphicon-ban-circle </li>
    <li class="search-show"><i class="glyphicon glyphicon-arrow-left " data-hex="&quot;\e091&quot;"></i>glyphicon glyphicon-arrow-left </li>
    <li class="search-show"><i class="glyphicon glyphicon-arrow-right " data-hex="&quot;\e092&quot;"></i>glyphicon glyphicon-arrow-right </li>
    <li class="search-show"><i class="glyphicon glyphicon-arrow-up " data-hex="&quot;\e093&quot;"></i>glyphicon glyphicon-arrow-up </li>
    <li class="search-show"><i class="glyphicon glyphicon-arrow-down " data-hex="&quot;\e094&quot;"></i>glyphicon glyphicon-arrow-down </li>
    <li class="search-show"><i class="glyphicon glyphicon-share-alt " data-hex="&quot;\e095&quot;"></i>glyphicon glyphicon-share-alt </li>
    <li class="search-show"><i class="glyphicon glyphicon-resize-full " data-hex="&quot;\e096&quot;"></i>glyphicon glyphicon-resize-full </li>
    <li class="search-show"><i class="glyphicon glyphicon-resize-small " data-hex="&quot;\e097&quot;"></i>glyphicon glyphicon-resize-small </li>
    <li class="search-show"><i class="glyphicon glyphicon-exclamation-sign " data-hex="&quot;\e101&quot;"></i>glyphicon glyphicon-exclamation-sign </li>
    <li class="search-show"><i class="glyphicon glyphicon-gift " data-hex="&quot;\e102&quot;"></i>glyphicon glyphicon-gift </li>
    <li class="search-show"><i class="glyphicon glyphicon-leaf " data-hex="&quot;\e103&quot;"></i>glyphicon glyphicon-leaf </li>
    <li class="search-show"><i class="glyphicon glyphicon-fire " data-hex="&quot;\e104&quot;"></i>glyphicon glyphicon-fire </li>
    <li class="search-show"><i class="glyphicon glyphicon-eye-open " data-hex="&quot;\e105&quot;"></i>glyphicon glyphicon-eye-open </li>
    <li class="search-show"><i class="glyphicon glyphicon-eye-close " data-hex="&quot;\e106&quot;"></i>glyphicon glyphicon-eye-close </li>
    <li class="search-show"><i class="glyphicon glyphicon-warning-sign " data-hex="&quot;\e107&quot;"></i>glyphicon glyphicon-warning-sign </li>
    <li class="search-show"><i class="glyphicon glyphicon-plane " data-hex="&quot;\e108&quot;"></i>glyphicon glyphicon-plane </li>
    <li class="search-show"><i class="glyphicon glyphicon-calendar " data-hex="&quot;\e109&quot;"></i>glyphicon glyphicon-calendar </li>
    <li class="search-show"><i class="glyphicon glyphicon-random " data-hex="&quot;\e110&quot;"></i>glyphicon glyphicon-random </li>
    <li class="search-show"><i class="glyphicon glyphicon-comment " data-hex="&quot;\e111&quot;"></i>glyphicon glyphicon-comment </li>
    <li class="search-show"><i class="glyphicon glyphicon-magnet " data-hex="&quot;\e112&quot;"></i>glyphicon glyphicon-magnet </li>
    <li class="search-show"><i class="glyphicon glyphicon-chevron-up " data-hex="&quot;\e113&quot;"></i>glyphicon glyphicon-chevron-up </li>
    <li class="search-show"><i class="glyphicon glyphicon-chevron-down " data-hex="&quot;\e114&quot;"></i>glyphicon glyphicon-chevron-down </li>
    <li class="search-show"><i class="glyphicon glyphicon-retweet " data-hex="&quot;\e115&quot;"></i>glyphicon glyphicon-retweet </li>
    <li class="search-show"><i class="glyphicon glyphicon-shopping-cart " data-hex="&quot;\e116&quot;"></i>glyphicon glyphicon-shopping-cart </li>
    <li class="search-show"><i class="glyphicon glyphicon-folder-close " data-hex="&quot;\e117&quot;"></i>glyphicon glyphicon-folder-close </li>
    <li class="search-show"><i class="glyphicon glyphicon-folder-open " data-hex="&quot;\e118&quot;"></i>glyphicon glyphicon-folder-open </li>
    <li class="search-show"><i class="glyphicon glyphicon-resize-vertical " data-hex="&quot;\e119&quot;"></i>glyphicon glyphicon-resize-vertical </li>
    <li class="search-show"><i class="glyphicon glyphicon-resize-horizontal " data-hex="&quot;\e120&quot;"></i>glyphicon glyphicon-resize-horizontal </li>
    <li class="search-show"><i class="glyphicon glyphicon-hdd " data-hex="&quot;\e121&quot;"></i>glyphicon glyphicon-hdd </li>
    <li class="search-show"><i class="glyphicon glyphicon-bullhorn " data-hex="&quot;\e122&quot;"></i>glyphicon glyphicon-bullhorn </li>
    <li class="search-show"><i class="glyphicon glyphicon-bell " data-hex="&quot;\e123&quot;"></i>glyphicon glyphicon-bell </li>
    <li class="search-show"><i class="glyphicon glyphicon-certificate " data-hex="&quot;\e124&quot;"></i>glyphicon glyphicon-certificate </li>
    <li class="search-show"><i class="glyphicon glyphicon-thumbs-up " data-hex="&quot;\e125&quot;"></i>glyphicon glyphicon-thumbs-up </li>
    <li class="search-show"><i class="glyphicon glyphicon-thumbs-down " data-hex="&quot;\e126&quot;"></i>glyphicon glyphicon-thumbs-down </li>
    <li class="search-show"><i class="glyphicon glyphicon-hand-right " data-hex="&quot;\e127&quot;"></i>glyphicon glyphicon-hand-right </li>
    <li class="search-show"><i class="glyphicon glyphicon-hand-left " data-hex="&quot;\e128&quot;"></i>glyphicon glyphicon-hand-left </li>
    <li class="search-show"><i class="glyphicon glyphicon-hand-up " data-hex="&quot;\e129&quot;"></i>glyphicon glyphicon-hand-up </li>
    <li class="search-show"><i class="glyphicon glyphicon-hand-down " data-hex="&quot;\e130&quot;"></i>glyphicon glyphicon-hand-down </li>
    <li class="search-show"><i class="glyphicon glyphicon-circle-arrow-right " data-hex="&quot;\e131&quot;"></i>glyphicon glyphicon-circle-arrow-right </li>
    <li class="search-show"><i class="glyphicon glyphicon-circle-arrow-left " data-hex="&quot;\e132&quot;"></i>glyphicon glyphicon-circle-arrow-left </li>
    <li class="search-show"><i class="glyphicon glyphicon-circle-arrow-up " data-hex="&quot;\e133&quot;"></i>glyphicon glyphicon-circle-arrow-up </li>
    <li class="search-show"><i class="glyphicon glyphicon-circle-arrow-down " data-hex="&quot;\e134&quot;"></i>glyphicon glyphicon-circle-arrow-down </li>
    <li class="search-show"><i class="glyphicon glyphicon-globe " data-hex="&quot;\e135&quot;"></i>glyphicon glyphicon-globe </li>
    <li class="search-show"><i class="glyphicon glyphicon-wrench " data-hex="&quot;\e136&quot;"></i>glyphicon glyphicon-wrench </li>
    <li class="search-show"><i class="glyphicon glyphicon-tasks " data-hex="&quot;\e137&quot;"></i>glyphicon glyphicon-tasks </li>
    <li class="search-show"><i class="glyphicon glyphicon-filter " data-hex="&quot;\e138&quot;"></i>glyphicon glyphicon-filter </li>
    <li class="search-show"><i class="glyphicon glyphicon-briefcase " data-hex="&quot;\e139&quot;"></i>glyphicon glyphicon-briefcase </li>
    <li class="search-show"><i class="glyphicon glyphicon-fullscreen " data-hex="&quot;\e140&quot;"></i>glyphicon glyphicon-fullscreen </li>
    <li class="search-show"><i class="glyphicon glyphicon-dashboard " data-hex="&quot;\e141&quot;"></i>glyphicon glyphicon-dashboard </li>
    <li class="search-show"><i class="glyphicon glyphicon-paperclip " data-hex="&quot;\e142&quot;"></i>glyphicon glyphicon-paperclip </li>
    <li class="search-show"><i class="glyphicon glyphicon-heart-empty " data-hex="&quot;\e143&quot;"></i>glyphicon glyphicon-heart-empty </li>
    <li class="search-show"><i class="glyphicon glyphicon-link " data-hex="&quot;\e144&quot;"></i>glyphicon glyphicon-link </li>
    <li class="search-show"><i class="glyphicon glyphicon-phone " data-hex="&quot;\e145&quot;"></i>glyphicon glyphicon-phone </li>
    <li class="search-show"><i class="glyphicon glyphicon-pushpin " data-hex="&quot;\e146&quot;"></i>glyphicon glyphicon-pushpin </li>
    <li class="search-show"><i class="glyphicon glyphicon-usd " data-hex="&quot;\e148&quot;"></i>glyphicon glyphicon-usd </li>
    <li class="search-show"><i class="glyphicon glyphicon-gbp " data-hex="&quot;\e149&quot;"></i>glyphicon glyphicon-gbp </li>
    <li class="search-show"><i class="glyphicon glyphicon-sort " data-hex="&quot;\e150&quot;"></i>glyphicon glyphicon-sort </li>
    <li class="search-show"><i class="glyphicon glyphicon-sort-by-alphabet " data-hex="&quot;\e151&quot;"></i>glyphicon glyphicon-sort-by-alphabet </li>
    <li class="search-show"><i class="glyphicon glyphicon-sort-by-alphabet-alt " data-hex="&quot;\e152&quot;"></i>glyphicon glyphicon-sort-by-alphabet-alt </li>
    <li class="search-show"><i class="glyphicon glyphicon-sort-by-order " data-hex="&quot;\e153&quot;"></i>glyphicon glyphicon-sort-by-order </li>
    <li class="search-show"><i class="glyphicon glyphicon-sort-by-order-alt " data-hex="&quot;\e154&quot;"></i>glyphicon glyphicon-sort-by-order-alt </li>
    <li class="search-show"><i class="glyphicon glyphicon-sort-by-attributes " data-hex="&quot;\e155&quot;"></i>glyphicon glyphicon-sort-by-attributes </li>
    <li class="search-show"><i class="glyphicon glyphicon-sort-by-attributes-alt " data-hex="&quot;\e156&quot;"></i>glyphicon glyphicon-sort-by-attributes-alt </li>
    <li class="search-show"><i class="glyphicon glyphicon-unchecked " data-hex="&quot;\e157&quot;"></i>glyphicon glyphicon-unchecked </li>
    <li class="search-show"><i class="glyphicon glyphicon-expand " data-hex="&quot;\e158&quot;"></i>glyphicon glyphicon-expand </li>
    <li class="search-show"><i class="glyphicon glyphicon-collapse-down " data-hex="&quot;\e159&quot;"></i>glyphicon glyphicon-collapse-down </li>
    <li class="search-show"><i class="glyphicon glyphicon-collapse-up " data-hex="&quot;\e160&quot;"></i>glyphicon glyphicon-collapse-up </li>
    <li class="search-show"><i class="glyphicon glyphicon-log-in " data-hex="&quot;\e161&quot;"></i>glyphicon glyphicon-log-in </li>
    <li class="search-show"><i class="glyphicon glyphicon-flash " data-hex="&quot;\e162&quot;"></i>glyphicon glyphicon-flash </li>
    <li class="search-show"><i class="glyphicon glyphicon-log-out " data-hex="&quot;\e163&quot;"></i>glyphicon glyphicon-log-out </li>
    <li class="search-show"><i class="glyphicon glyphicon-new-window " data-hex="&quot;\e164&quot;"></i>glyphicon glyphicon-new-window </li>
    <li class="search-show"><i class="glyphicon glyphicon-record " data-hex="&quot;\e165&quot;"></i>glyphicon glyphicon-record </li>
    <li class="search-show"><i class="glyphicon glyphicon-save " data-hex="&quot;\e166&quot;"></i>glyphicon glyphicon-save </li>
    <li class="search-show"><i class="glyphicon glyphicon-open " data-hex="&quot;\e167&quot;"></i>glyphicon glyphicon-open </li>
    <li class="search-show"><i class="glyphicon glyphicon-saved " data-hex="&quot;\e168&quot;"></i>glyphicon glyphicon-saved </li>
    <li class="search-show"><i class="glyphicon glyphicon-import " data-hex="&quot;\e169&quot;"></i>glyphicon glyphicon-import </li>
    <li class="search-show"><i class="glyphicon glyphicon-export " data-hex="&quot;\e170&quot;"></i>glyphicon glyphicon-export </li>
    <li class="search-show"><i class="glyphicon glyphicon-send " data-hex="&quot;\e171&quot;"></i>glyphicon glyphicon-send </li>
    <li class="search-show"><i class="glyphicon glyphicon-floppy-disk " data-hex="&quot;\e172&quot;"></i>glyphicon glyphicon-floppy-disk </li>
    <li class="search-show"><i class="glyphicon glyphicon-floppy-saved " data-hex="&quot;\e173&quot;"></i>glyphicon glyphicon-floppy-saved </li>
    <li class="search-show"><i class="glyphicon glyphicon-floppy-remove " data-hex="&quot;\e174&quot;"></i>glyphicon glyphicon-floppy-remove </li>
    <li class="search-show"><i class="glyphicon glyphicon-floppy-save " data-hex="&quot;\e175&quot;"></i>glyphicon glyphicon-floppy-save </li>
    <li class="search-show"><i class="glyphicon glyphicon-floppy-open " data-hex="&quot;\e176&quot;"></i>glyphicon glyphicon-floppy-open </li>
    <li class="search-show"><i class="glyphicon glyphicon-credit-card " data-hex="&quot;\e177&quot;"></i>glyphicon glyphicon-credit-card </li>
    <li class="search-show"><i class="glyphicon glyphicon-transfer " data-hex="&quot;\e178&quot;"></i>glyphicon glyphicon-transfer </li>
    <li class="search-show"><i class="glyphicon glyphicon-cutlery " data-hex="&quot;\e179&quot;"></i>glyphicon glyphicon-cutlery </li>
    <li class="search-show"><i class="glyphicon glyphicon-header " data-hex="&quot;\e180&quot;"></i>glyphicon glyphicon-header </li>
    <li class="search-show"><i class="glyphicon glyphicon-compressed " data-hex="&quot;\e181&quot;"></i>glyphicon glyphicon-compressed </li>
    <li class="search-show"><i class="glyphicon glyphicon-earphone " data-hex="&quot;\e182&quot;"></i>glyphicon glyphicon-earphone </li>
    <li class="search-show"><i class="glyphicon glyphicon-phone-alt " data-hex="&quot;\e183&quot;"></i>glyphicon glyphicon-phone-alt </li>
    <li class="search-show"><i class="glyphicon glyphicon-tower " data-hex="&quot;\e184&quot;"></i>glyphicon glyphicon-tower </li>
    <li class="search-show"><i class="glyphicon glyphicon-stats " data-hex="&quot;\e185&quot;"></i>glyphicon glyphicon-stats </li>
    <li class="search-show"><i class="glyphicon glyphicon-sd-video " data-hex="&quot;\e186&quot;"></i>glyphicon glyphicon-sd-video </li>
    <li class="search-show"><i class="glyphicon glyphicon-hd-video " data-hex="&quot;\e187&quot;"></i>glyphicon glyphicon-hd-video </li>
    <li class="search-show"><i class="glyphicon glyphicon-subtitles " data-hex="&quot;\e188&quot;"></i>glyphicon glyphicon-subtitles </li>
    <li class="search-show"><i class="glyphicon glyphicon-sound-stereo " data-hex="&quot;\e189&quot;"></i>glyphicon glyphicon-sound-stereo </li>
    <li class="search-show"><i class="glyphicon glyphicon-sound-dolby " data-hex="&quot;\e190&quot;"></i>glyphicon glyphicon-sound-dolby </li>
    <li class="search-show"><i class="glyphicon glyphicon-sound-5-1 " data-hex="&quot;\e191&quot;"></i>glyphicon glyphicon-sound-5-1 </li>
    <li class="search-show"><i class="glyphicon glyphicon-sound-6-1 " data-hex="&quot;\e192&quot;"></i>glyphicon glyphicon-sound-6-1 </li>
    <li class="search-show"><i class="glyphicon glyphicon-sound-7-1 " data-hex="&quot;\e193&quot;"></i>glyphicon glyphicon-sound-7-1 </li>
    <li class="search-show"><i class="glyphicon glyphicon-copyright-mark " data-hex="&quot;\e194&quot;"></i>glyphicon glyphicon-copyright-mark </li>
    <li class="search-show"><i class="glyphicon glyphicon-registration-mark " data-hex="&quot;\e195&quot;"></i>glyphicon glyphicon-registration-mark </li>
    <li class="search-show"><i class="glyphicon glyphicon-cloud-download " data-hex="&quot;\e197&quot;"></i>glyphicon glyphicon-cloud-download </li>
    <li class="search-show"><i class="glyphicon glyphicon-cloud-upload " data-hex="&quot;\e198&quot;"></i>glyphicon glyphicon-cloud-upload </li>
    <li class="search-show"><i class="glyphicon glyphicon-tree-conifer " data-hex="&quot;\e199&quot;"></i>glyphicon glyphicon-tree-conifer </li>
    <li class="search-show"><i class="glyphicon glyphicon-tree-deciduous " data-hex="&quot;\e200&quot;"></i>glyphicon glyphicon-tree-deciduous </li>
   </ul>