<ul id="simplelineicons" class="list-icon localsearch" data-font="Simple-Line-Icons">
	<li class="search-show"><i class="icon-user-female" data-hex="&quot;\e000&quot;"></i>icon-user-female</li>
	<li class="search-show"><i class="icon-user-follow" data-hex="&quot;\e002&quot;"></i>icon-user-follow</li>
	<li class="search-show"><i class="icon-user-following" data-hex="&quot;\e003&quot;"></i>icon-user-following</li>
	<li class="search-show"><i class="icon-user-unfollow" data-hex="&quot;\e004&quot;"></i>icon-user-unfollow</li>
	<li class="search-show"><i class="icon-trophy" data-hex="&quot;\e006&quot;"></i>icon-trophy</li>
	<li class="search-show"><i class="icon-screen-smartphone" data-hex="&quot;\e010&quot;"></i>icon-screen-smartphone</li>
	<li class="search-show"><i class="icon-screen-desktop" data-hex="&quot;\e011&quot;"></i>icon-screen-desktop</li>
	<li class="search-show"><i class="icon-plane" data-hex="&quot;\e012&quot;"></i>icon-plane</li>
	<li class="search-show"><i class="icon-notebook" data-hex="&quot;\e013&quot;"></i>icon-notebook</li>
	<li class="search-show"><i class="icon-moustache" data-hex="&quot;\e014&quot;"></i>icon-moustache</li>
	<li class="search-show"><i class="icon-mouse" data-hex="&quot;\e015&quot;"></i>icon-mouse</li>
	<li class="search-show"><i class="icon-magnet" data-hex="&quot;\e016&quot;"></i>icon-magnet</li>
	<li class="search-show"><i class="icon-energy" data-hex="&quot;\e020&quot;"></i>icon-energy</li>
	<li class="search-show"><i class="icon-emoticon-smile" data-hex="&quot;\e021&quot;"></i>icon-emoticon-smile</li>
	<li class="search-show"><i class="icon-disc" data-hex="&quot;\e022&quot;"></i>icon-disc</li>
	<li class="search-show"><i class="icon-cursor-move" data-hex="&quot;\e023&quot;"></i>icon-cursor-move</li>
	<li class="search-show"><i class="icon-crop" data-hex="&quot;\e024&quot;"></i>icon-crop</li>
	<li class="search-show"><i class="icon-credit-card" data-hex="&quot;\e025&quot;"></i>icon-credit-card</li>
	<li class="search-show"><i class="icon-chemistry" data-hex="&quot;\e026&quot;"></i>icon-chemistry</li>
	<li class="search-show"><i class="icon-user" data-hex="&quot;\e005&quot;"></i>icon-user</li>
	<li class="search-show"><i class="icon-speedometer" data-hex="&quot;\e007&quot;"></i>icon-speedometer</li>
	<li class="search-show"><i class="icon-social-youtube" data-hex="&quot;\e008&quot;"></i>icon-social-youtube</li>
	<li class="search-show"><i class="icon-social-twitter" data-hex="&quot;\e009&quot;"></i>icon-social-twitter</li>
	<li class="search-show"><i class="icon-social-tumblr" data-hex="&quot;\e00a&quot;"></i>icon-social-tumblr</li>
	<li class="search-show"><i class="icon-social-facebook" data-hex="&quot;\e00b&quot;"></i>icon-social-facebook</li>
	<li class="search-show"><i class="icon-social-dropbox" data-hex="&quot;\e00c&quot;"></i>icon-social-dropbox</li>
	<li class="search-show"><i class="icon-social-dribbble" data-hex="&quot;\e00d&quot;"></i>icon-social-dribbble</li>
	<li class="search-show"><i class="icon-shield" data-hex="&quot;\e00e&quot;"></i>icon-shield</li>
	<li class="search-show"><i class="icon-screen-tablet" data-hex="&quot;\e00f&quot;"></i>icon-screen-tablet</li>
	<li class="search-show"><i class="icon-magic-wand" data-hex="&quot;\e017&quot;"></i>icon-magic-wand</li>
	<li class="search-show"><i class="icon-hourglass" data-hex="&quot;\e018&quot;"></i>icon-hourglass</li>
	<li class="search-show"><i class="icon-graduation" data-hex="&quot;\e019&quot;"></i>icon-graduation</li>
	<li class="search-show"><i class="icon-ghost" data-hex="&quot;\e01a&quot;"></i>icon-ghost</li>
	<li class="search-show"><i class="icon-game-controller" data-hex="&quot;\e01b&quot;"></i>icon-game-controller</li>
	<li class="search-show"><i class="icon-fire" data-hex="&quot;\e01c&quot;"></i>icon-fire</li>
	<li class="search-show"><i class="icon-eyeglasses" data-hex="&quot;\e01d&quot;"></i>icon-eyeglasses</li>
	<li class="search-show"><i class="icon-envelope-open" data-hex="&quot;\e01e&quot;"></i>icon-envelope-open</li>
	<li class="search-show"><i class="icon-envelope-letter" data-hex="&quot;\e01f&quot;"></i>icon-envelope-letter</li>
	<li class="search-show"><i class="icon-bell" data-hex="&quot;\e027&quot;"></i>icon-bell</li>
	<li class="search-show"><i class="icon-badge" data-hex="&quot;\e028&quot;"></i>icon-badge</li>
	<li class="search-show"><i class="icon-anchor" data-hex="&quot;\e029&quot;"></i>icon-anchor</li>
	<li class="search-show"><i class="icon-wallet" data-hex="&quot;\e02a&quot;"></i>icon-wallet</li>
	<li class="search-show"><i class="icon-vector" data-hex="&quot;\e02b&quot;"></i>icon-vector</li>
	<li class="search-show"><i class="icon-speech" data-hex="&quot;\e02c&quot;"></i>icon-speech</li>
	<li class="search-show"><i class="icon-puzzle" data-hex="&quot;\e02d&quot;"></i>icon-puzzle</li>
	<li class="search-show"><i class="icon-printer" data-hex="&quot;\e02e&quot;"></i>icon-printer</li>
	<li class="search-show"><i class="icon-present" data-hex="&quot;\e02f&quot;"></i>icon-present</li>
	<li class="search-show"><i class="icon-playlist" data-hex="&quot;\e030&quot;"></i>icon-playlist</li>
	<li class="search-show"><i class="icon-pin" data-hex="&quot;\e031&quot;"></i>icon-pin</li>
	<li class="search-show"><i class="icon-picture" data-hex="&quot;\e032&quot;"></i>icon-picture</li>
	<li class="search-show"><i class="icon-map" data-hex="&quot;\e033&quot;"></i>icon-map</li>
	<li class="search-show"><i class="icon-layers" data-hex="&quot;\e034&quot;"></i>icon-layers</li>
	<li class="search-show"><i class="icon-handbag" data-hex="&quot;\e035&quot;"></i>icon-handbag</li>
	<li class="search-show"><i class="icon-globe-alt" data-hex="&quot;\e036&quot;"></i>icon-globe-alt</li>
	<li class="search-show"><i class="icon-globe" data-hex="&quot;\e037&quot;"></i>icon-globe</li>
	<li class="search-show"><i class="icon-frame" data-hex="&quot;\e038&quot;"></i>icon-frame</li>
	<li class="search-show"><i class="icon-folder-alt" data-hex="&quot;\e039&quot;"></i>icon-folder-alt</li>
	<li class="search-show"><i class="icon-film" data-hex="&quot;\e03a&quot;"></i>icon-film</li>
	<li class="search-show"><i class="icon-feed" data-hex="&quot;\e03b&quot;"></i>icon-feed</li>
	<li class="search-show"><i class="icon-earphones-alt" data-hex="&quot;\e03c&quot;"></i>icon-earphones-alt</li>
	<li class="search-show"><i class="icon-earphones" data-hex="&quot;\e03d&quot;"></i>icon-earphones</li>
	<li class="search-show"><i class="icon-drop" data-hex="&quot;\e03e&quot;"></i>icon-drop</li>
	<li class="search-show"><i class="icon-drawer" data-hex="&quot;\e03f&quot;"></i>icon-drawer</li>
	<li class="search-show"><i class="icon-docs" data-hex="&quot;\e040&quot;"></i>icon-docs</li>
	<li class="search-show"><i class="icon-directions" data-hex="&quot;\e041&quot;"></i>icon-directions</li>
	<li class="search-show"><i class="icon-direction" data-hex="&quot;\e042&quot;"></i>icon-direction</li>
	<li class="search-show"><i class="icon-diamond" data-hex="&quot;\e043&quot;"></i>icon-diamond</li>
	<li class="search-show"><i class="icon-cup" data-hex="&quot;\e044&quot;"></i>icon-cup</li>
	<li class="search-show"><i class="icon-compass" data-hex="&quot;\e045&quot;"></i>icon-compass</li>
	<li class="search-show"><i class="icon-call-out" data-hex="&quot;\e046&quot;"></i>icon-call-out</li>
	<li class="search-show"><i class="icon-call-in" data-hex="&quot;\e047&quot;"></i>icon-call-in</li>
	<li class="search-show"><i class="icon-call-end" data-hex="&quot;\e048&quot;"></i>icon-call-end</li>
	<li class="search-show"><i class="icon-calculator" data-hex="&quot;\e049&quot;"></i>icon-calculator</li>
	<li class="search-show"><i class="icon-bubbles" data-hex="&quot;\e04a&quot;"></i>icon-bubbles</li>
	<li class="search-show"><i class="icon-briefcase" data-hex="&quot;\e04b&quot;"></i>icon-briefcase</li>
	<li class="search-show"><i class="icon-book-open" data-hex="&quot;\e04c&quot;"></i>icon-book-open</li>
	<li class="search-show"><i class="icon-basket-loaded" data-hex="&quot;\e04d&quot;"></i>icon-basket-loaded</li>
	<li class="search-show"><i class="icon-basket" data-hex="&quot;\e04e&quot;"></i>icon-basket</li>
	<li class="search-show"><i class="icon-bag" data-hex="&quot;\e04f&quot;"></i>icon-bag</li>
	<li class="search-show"><i class="icon-action-undo" data-hex="&quot;\e050&quot;"></i>icon-action-undo</li>
	<li class="search-show"><i class="icon-action-redo" data-hex="&quot;\e051&quot;"></i>icon-action-redo</li>
	<li class="search-show"><i class="icon-wrench" data-hex="&quot;\e052&quot;"></i>icon-wrench</li>
	<li class="search-show"><i class="icon-umbrella" data-hex="&quot;\e053&quot;"></i>icon-umbrella</li>
	<li class="search-show"><i class="icon-trash" data-hex="&quot;\e054&quot;"></i>icon-trash</li>
	<li class="search-show"><i class="icon-tag" data-hex="&quot;\e055&quot;"></i>icon-tag</li>
	<li class="search-show"><i class="icon-support" data-hex="&quot;\e056&quot;"></i>icon-support</li>
	<li class="search-show"><i class="icon-size-fullscreen" data-hex="&quot;\e057&quot;"></i>icon-size-fullscreen</li>
	<li class="search-show"><i class="icon-size-actual" data-hex="&quot;\e058&quot;"></i>icon-size-actual</li>
	<li class="search-show"><i class="icon-shuffle" data-hex="&quot;\e059&quot;"></i>icon-shuffle</li>
	<li class="search-show"><i class="icon-share-alt" data-hex="&quot;\e05a&quot;"></i>icon-share-alt</li>
	<li class="search-show"><i class="icon-share" data-hex="&quot;\e05b&quot;"></i>icon-share</li>
	<li class="search-show"><i class="icon-rocket" data-hex="&quot;\e05c&quot;"></i>icon-rocket</li>
	<li class="search-show"><i class="icon-question" data-hex="&quot;\e05d&quot;"></i>icon-question</li>
	<li class="search-show"><i class="icon-pie-chart" data-hex="&quot;\e05e&quot;"></i>icon-pie-chart</li>
	<li class="search-show"><i class="icon-pencil" data-hex="&quot;\e05f&quot;"></i>icon-pencil</li>
	<li class="search-show"><i class="icon-note" data-hex="&quot;\e060&quot;"></i>icon-note</li>
	<li class="search-show"><i class="icon-music-tone-alt" data-hex="&quot;\e061&quot;"></i>icon-music-tone-alt</li>
	<li class="search-show"><i class="icon-music-tone" data-hex="&quot;\e062&quot;"></i>icon-music-tone</li>
	<li class="search-show"><i class="icon-microphone" data-hex="&quot;\e063&quot;"></i>icon-microphone</li>
	<li class="search-show"><i class="icon-loop" data-hex="&quot;\e064&quot;"></i>icon-loop</li>
	<li class="search-show"><i class="icon-logout" data-hex="&quot;\e065&quot;"></i>icon-logout</li>
	<li class="search-show"><i class="icon-login" data-hex="&quot;\e066&quot;"></i>icon-login</li>
	<li class="search-show"><i class="icon-list" data-hex="&quot;\e067&quot;"></i>icon-list</li>
	<li class="search-show"><i class="icon-like" data-hex="&quot;\e068&quot;"></i>icon-like</li>
	<li class="search-show"><i class="icon-home" data-hex="&quot;\e069&quot;"></i>icon-home</li>
	<li class="search-show"><i class="icon-grid" data-hex="&quot;\e06a&quot;"></i>icon-grid</li>
	<li class="search-show"><i class="icon-graph" data-hex="&quot;\e06b&quot;"></i>icon-graph</li>
	<li class="search-show"><i class="icon-equalizer" data-hex="&quot;\e06c&quot;"></i>icon-equalizer</li>
	<li class="search-show"><i class="icon-dislike" data-hex="&quot;\e06d&quot;"></i>icon-dislike</li>
	<li class="search-show"><i class="icon-cursor" data-hex="&quot;\e06e&quot;"></i>icon-cursor</li>
	<li class="search-show"><i class="icon-control-start" data-hex="&quot;\e06f&quot;"></i>icon-control-start</li>
	<li class="search-show"><i class="icon-control-rewind" data-hex="&quot;\e070&quot;"></i>icon-control-rewind</li>
	<li class="search-show"><i class="icon-control-play" data-hex="&quot;\e071&quot;"></i>icon-control-play</li>
	<li class="search-show"><i class="icon-control-pause" data-hex="&quot;\e072&quot;"></i>icon-control-pause</li>
	<li class="search-show"><i class="icon-control-forward" data-hex="&quot;\e073&quot;"></i>icon-control-forward</li>
	<li class="search-show"><i class="icon-control-end" data-hex="&quot;\e074&quot;"></i>icon-control-end</li>
	<li class="search-show"><i class="icon-calendar" data-hex="&quot;\e075&quot;"></i>icon-calendar</li>
	<li class="search-show"><i class="icon-bulb" data-hex="&quot;\e076&quot;"></i>icon-bulb</li>
	<li class="search-show"><i class="icon-bar-chart" data-hex="&quot;\e077&quot;"></i>icon-bar-chart</li>
	<li class="search-show"><i class="icon-arrow-up" data-hex="&quot;\e078&quot;"></i>icon-arrow-up</li>
	<li class="search-show"><i class="icon-arrow-right" data-hex="&quot;\e079&quot;"></i>icon-arrow-right</li>
	<li class="search-show"><i class="icon-arrow-left" data-hex="&quot;\e07a&quot;"></i>icon-arrow-left</li>
	<li class="search-show"><i class="icon-arrow-down" data-hex="&quot;\e07b&quot;"></i>icon-arrow-down</li>
	<li class="search-show"><i class="icon-ban" data-hex="&quot;\e07c&quot;"></i>icon-ban</li>
	<li class="search-show"><i class="icon-bubble" data-hex="&quot;\e07d&quot;"></i>icon-bubble</li>
	<li class="search-show"><i class="icon-camcorder" data-hex="&quot;\e07e&quot;"></i>icon-camcorder</li>
	<li class="search-show"><i class="icon-camera" data-hex="&quot;\e07f&quot;"></i>icon-camera</li>
	<li class="search-show"><i class="icon-check" data-hex="&quot;\e080&quot;"></i>icon-check</li>
	<li class="search-show"><i class="icon-clock" data-hex="&quot;\e081&quot;"></i>icon-clock</li>
	<li class="search-show"><i class="icon-close" data-hex="&quot;\e082&quot;"></i>icon-close</li>
	<li class="search-show"><i class="icon-cloud-download" data-hex="&quot;\e083&quot;"></i>icon-cloud-download</li>
	<li class="search-show"><i class="icon-cloud-upload" data-hex="&quot;\e084&quot;"></i>icon-cloud-upload</li>
	<li class="search-show"><i class="icon-doc" data-hex="&quot;\e085&quot;"></i>icon-doc</li>
	<li class="search-show"><i class="icon-envelope" data-hex="&quot;\e086&quot;"></i>icon-envelope</li>
	<li class="search-show"><i class="icon-eye" data-hex="&quot;\e087&quot;"></i>icon-eye</li>
	<li class="search-show"><i class="icon-flag" data-hex="&quot;\e088&quot;"></i>icon-flag</li>
	<li class="search-show"><i class="icon-folder" data-hex="&quot;\e089&quot;"></i>icon-folder</li>
	<li class="search-show"><i class="icon-heart" data-hex="&quot;\e08a&quot;"></i>icon-heart</li>
	<li class="search-show"><i class="icon-info" data-hex="&quot;\e08b&quot;"></i>icon-info</li>
	<li class="search-show"><i class="icon-key" data-hex="&quot;\e08c&quot;"></i>icon-key</li>
	<li class="search-show"><i class="icon-link" data-hex="&quot;\e08d&quot;"></i>icon-link</li>
	<li class="search-show"><i class="icon-lock" data-hex="&quot;\e08e&quot;"></i>icon-lock</li>
	<li class="search-show"><i class="icon-lock-open" data-hex="&quot;\e08f&quot;"></i>icon-lock-open</li>
	<li class="search-show"><i class="icon-magnifier" data-hex="&quot;\e090&quot;"></i>icon-magnifier</li>
	<li class="search-show"><i class="icon-magnifier-add" data-hex="&quot;\e091&quot;"></i>icon-magnifier-add</li>
	<li class="search-show"><i class="icon-magnifier-remove" data-hex="&quot;\e092&quot;"></i>icon-magnifier-remove</li>
	<li class="search-show"><i class="icon-paper-clip" data-hex="&quot;\e093&quot;"></i>icon-paper-clip</li>
	<li class="search-show"><i class="icon-paper-plane" data-hex="&quot;\e094&quot;"></i>icon-paper-plane</li>
	<li class="search-show"><i class="icon-plus" data-hex="&quot;\e095&quot;"></i>icon-plus</li>
	<li class="search-show"><i class="icon-pointer" data-hex="&quot;\e096&quot;"></i>icon-pointer</li>
	<li class="search-show"><i class="icon-power" data-hex="&quot;\e097&quot;"></i>icon-power</li>
	<li class="search-show"><i class="icon-refresh" data-hex="&quot;\e098&quot;"></i>icon-refresh</li>
	<li class="search-show"><i class="icon-reload" data-hex="&quot;\e099&quot;"></i>icon-reload</li>
	<li class="search-show"><i class="icon-settings" data-hex="&quot;\e09a&quot;"></i>icon-settings</li>
	<li class="search-show"><i class="icon-star" data-hex="&quot;\e09b&quot;"></i>icon-star</li>
	<li class="search-show"><i class="icon-symbol-female" data-hex="&quot;\e09c&quot;"></i>icon-symbol-female</li>
	<li class="search-show"><i class="icon-symbol-male" data-hex="&quot;\e09d&quot;"></i>icon-symbol-male</li>
	<li class="search-show"><i class="icon-target" data-hex="&quot;\e09e&quot;"></i>icon-target</li>
	<li class="search-show"><i class="icon-volume-1" data-hex="&quot;\e09f&quot;"></i>icon-volume-1</li>
	<li class="search-show"><i class="icon-volume-2" data-hex="&quot;\e0a0&quot;"></i>icon-volume-2</li>
	<li class="search-show"><i class="icon-volume-off" data-hex="&quot;\e0a1&quot;"></i>icon-volume-off</li>
	<li class="search-show"><i class="icon-users" data-hex="&quot;\e001&quot;"></i>icon-users</li></ul>